apiVersion: apps/v1
kind: Deployment
metadata:
  name: docker-angular-deployment
spec:
  selector:
    matchLabels:
      app: docker-angular-pod
  template:
    metadata:
      labels:
        app: docker-angular-pod
    spec:
      containers:
      - name: docker-angular-container
        image: contenedorregistrodesarrollo.azurecr.io/huasquino/docker-angular:v#{Build.BuildId}#
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
kind: Service
apiVersion: v1 
metadata:
  name: docker-angular-service
spec:
  selector:
    app: docker-angular-pod
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
